### ISSUE TITLE
 drag&drop install not working

### ISSUE THREAD

**Issue by j-ruck** [joomla-agency/plg_jooag_shariff#1]
I downloaded the latest version as a ZIP and tried to install this via the drag&drop Package File Upload. 
I get the following error messages:

> Warning
> JInstaller: :Install: Can't find Joomla XML setup file.
> Error
> Unable to find install package

The Joomla version is 3.8.7

Last week there was a different error message (something like "/css not found") which also had an issue opened here, but which has since been closed.

**Comment by ufuk-avcu** [comment]
Hey. Please use this here: https://github.com/joomla-agency/plg_jooag_shariff/releases
