### ISSUE TITLE
Make cache adapter selectable

### ISSUE THREAD

**Issue by CommanderBond** [joomla-agency/plg_jooag_shariff#10]
Shariff Framework uses ZendFramework that supports a variety of cache adapters for Shariff (thats awesome!).
By default file cache is always used. However, the server may have installed another (faster) cache manager like WinCache.

Maybe a dropdown with all available cache managers would be useful to enable the administrator to choose one of them. However, not all of them are available on all systems (WinCache just on Windows servers, others are exclusively available on Linux boxes).
Perhaps it would also be sufficient to set plugin's cache adapter to WinCache, if "Windows Cache" was selected in Joomla system configuration cache setings. This would not allow to use another one, though.

What about that?

Thanks!

**Comment by joomla-agency** [comment]
Implented in https://github.com/joomla-agency/plg_jooag_shariff/commit/fa59c2ff18fa94532a4196b7ace89c1a4bb70109

**Comment by joomla-agency** [comment]
Fixed file != filesystem problem here: https://github.com/joomla-agency/plg_jooag_shariff/commit/581df6124e9e17562fd60d4b586be25dd6ebb639

**Comment by CommanderBond** [comment]
Confirming fixed issue after manually applying code from https://github.com/joomla-agency/plg_jooag_shariff/commit/581df6124e9e17562fd60d4b586be25dd6ebb639
