### ISSUE TITLE
Localization Not Working Correctly

### ISSUE THREAD

**Issue by jngr** [joomla-agency/plg_jooag_shariff#12]
Thank you for sharing this Shariff plugin for Joomla.

The buttons are not correctly translated, and it seems like an issue with detecting the page's locale. Inspecting the source of a Finnish web page shows
`<div class="shariff" data-lang="finnish-fi" ...>`
while, according to Shariff documentation, the language tag should be as follows:
`data-lang="fi"`
and, indeed, hard-coding the locale fixes the problem. Perhaps the language/locale detection should be checked to make a more solid fix.

-jngr

**Comment by ufuk-avcu** [comment]
Hi. Can you go please to this site: xxxyourdomainyyyy.tld/administrator/index.php?option=com_languages&view=languages and look for the URL Language Code. This value is used by my Plugin. There should be something like en, de, fi...

**Comment by jngr** [comment]
Thanks for your response. There is one entry for the Finnish language, language code `fi` in the content language list.

**Comment by ufuk-avcu** [comment]
Can you please test the newest Master Version. It should be fixed now.

**Comment by jngr** [comment]
Yep, that solved it. Thank you!
