### ISSUE TITLE
Missing argument 4 in onContentBeforeDisplay and onContentAfterDisplay

### ISSUE THREAD

**Issue by bertmert** [joomla-agency/plg_jooag_shariff#15]
After update to version 3.2.3 and with error_reporting = maximum I see lots of these warnings in my media manager (backend) when I want to insert an article image

Warning: Missing argument 4 for plgSystemJooag_Shariff::onContentAfterDisplay() in /plugins/system/jooag_shariff/jooag_shariff.php on line 52

Warning: Missing argument 4 for plgSystemJooag_Shariff::onContentBeforeDisplay() in /plugins/system/jooag_shariff/jooag_shariff.php on line 29

![jooag](https://cloud.githubusercontent.com/assets/11038612/9382172/768cbd1e-473e-11e5-864f-8b3e7de6961d.png)

**Comment by bertmert** [comment]
Because I don't know which branch to use for PRs. This fixes the issue (default value 0 for $page):

```
public function onContentBeforeDisplay($context, &$article, &$params, $page = 0)
```

```
public function onContentAfterDisplay($context, &$article, &$params, $page = 0)
```

**Comment by ufuk-avcu** [comment]
Thank you. Should be fixed now. Can you test the new Master branch?
