### ISSUE TITLE
Whatsapp button only on mobile

### ISSUE THREAD

**Issue by derChristoph** [joomla-agency/plg_jooag_shariff#16]
is is posible to activate the whatsapp button only on Mobile?
With an Bootstrap class="hidden-xs" for example?

**Comment by ufuk-avcu** [comment]
Off course it's possible, but i have decided to support the official Heise Shariff functionality, without extending it. You can open an Issue here: https://github.com/heiseonline/shariff Maybe the nice people there, accept your request...

**Comment by ufuk-avcu** [comment]
See this also: https://github.com/heiseonline/shariff/issues/119
