### ISSUE TITLE
plg_jooag_sharif and Joomla 4

### ISSUE THREAD

**Issue by tramber91** [joomla-agency/plg_jooag_shariff#17]
Hi

Your plugin will be Joomla 4 ready ?
Thanks

Bertrand

**Comment by ufuk-avcu** [comment]
Hey,

can you please test the newest Master. It should work with Joomla 4 now.

Best Regards

**Comment by tramber91** [comment]
Hi thanks for your quick reply, I cannot test right now with Joomla 4. I have no site upgrade to this version. But update with master OK and works with joomla 3.10.0
Need date and version update (xml)
take care

**Comment by tramber91** [comment]
Check on a fresh Joomla4 install
Installation OK
Usage OK
https://joomla4.en-toutes-lettres.fr/blog/bienvenue-sur-votre-blog
thanks

**Comment by dermaxem** [comment]
Installed the 6.0.0 in a J4.2.2
I have errors at saving config like "Attempt to assign property "cacheDir" on null". 
Happen if i add a service like "print" oder "WhatsApp" and click "save".
PHP 8.0.20
Joomla! 4.2.2 Stable

**Comment by ufuk-avcu** [comment]
@dermaxem please use the latest Master again and please report it back, if the Problem occurs.
