### ISSUE TITLE
mail button issue

### ISSUE THREAD

**Issue by Gitjk** [joomla-agency/plg_jooag_shariff#17]
If I enable the selected mail icon on a Joomla 3.4.4 website with php 5.5.x, the icon changes itself to Google+ most of the time.

Also, it's not clear to me why I should enter an email address in the plugin settings. Can't get the mail button to work as expected. If I understand shariff correctly, the mail button is supposed to trigger a 'Recommend to a friend' email form, similar to the one used on the heise.de website.

**Comment by ufuk-avcu** [comment]
This should solved in the newest internal development version.

**Comment by Gitjk** [comment]
> This should solved in the newest internal development version.
Couldn't test it right away because I'm still forced to use php 5.4.x.  :-)
