### ISSUE TITLE
Display Buttons in Blog Layout?

### ISSUE THREAD

**Issue by flosen90** [joomla-agency/plg_jooag_shariff#21]
It woult be nice if the plugin wouldn't only show up in article view, but also in blog view.
If I change the if($context == 'com_content.article' ... the buttons are displayed after each item, but always the URL from the blog page (and not from the article) is used.
Would be great, if user con modify in wich layout buttons are shown!
Thanks

**Comment by ufuk-avcu** [comment]
Thank you! For the next version this would archived! You can choose, if you put the Shariff output in Articles or Categories or both.
