### ISSUE TITLE
PHP 8.x support?

### ISSUE THREAD

**Issue by TheSoulrester** [joomla-agency/plg_jooag_shariff#21]
Hey there :)

in the readme it says that this plugin is only PHP 7.x compatible
https://github.com/joomla-agency/plg_jooag_shariff/blob/master/README.md?plain=1#L10

Is this right? If true, will there be any PHP 8.x compatible version soon?

Due to Akeeba Backup, we have to switch over to PHP 8.0 soon because Akeeba Backup will stop working in November while using an older PHP version.

**Comment by ufuk-avcu** [comment]
It should work now with PHP 8.0. Please test the latest Master Version
