### ISSUE TITLE
Embedd Like

### ISSUE THREAD

**Issue by vhmrde** [joomla-agency/plg_jooag_shariff#27]
Heise schreibt etwas davon, ass Shariff die Zwei-Klick Lösung ersetzt. DAs ist in meinen Augen nicht richtig. Zwar werden die Likes angezeigt, man kann aber den Beitrag nicht liken, pluseinsen oder sonstwas. Nur Teilen.

Schön wäre, wenn man dies mit einbauen könnte!

Grüße

**Comment by ufuk-avcu** [comment]
Hallo. Das kannst du gerne bei https://github.com/heiseonline/shariff anregen. Sollte es dort umgesetzt werden, so werde ich es ebenso adaptieren.
