### ISSUE TITLE
email

### ISSUE THREAD

**Issue by joit** [joomla-agency/plg_jooag_shariff#29]
Email funktioniert nur, wenn man einen Empfänger angibt, sonst gibt’s error 500

**Comment by ufuk-avcu** [comment]
Die Mail Funktion habe ich mal überarbeitet. So richtig funktioniert das in Joomla 3 nicht, da wir keine "Sende diese Seite per Mail an yxz" mehr haben. Daher kann man einfach da ein URL zu einem Formular angeben und die Leute können, dann eine Nachricht schicken. Wenn du testen magst: https://github.com/joomla-agency/plg_jooag_shariff/releases/tag/3.3.0Beta2
