### ISSUE TITLE
use https instead of http @ linkedin

### ISSUE THREAD

**Issue by cn-tools** [joomla-agency/plg_jooag_shariff#3]
in both files in folder "plg_jooag_shariff/assets/js" you use the http protocol instead the https protocol for linkedin

**Comment by joomla-agency** [comment]
Hi. The assets came from https://github.com/heiseonline/shariff . Can you open a issue (when it is) there for this?

**Comment by joomla-agency** [comment]
I see this is solved already in the newest version. We need to wait for a new shariff Release and then i can merge this.

**Comment by cn-tools** [comment]
ok perfekt ... thx 4 fast answer
and congrats for this awesome plugin
