### ISSUE TITLE
Various Issues With .htacces Rewrite Rule non-www to www

### ISSUE THREAD

**Issue by dautrich** [joomla-agency/plg_jooag_shariff#31]
I installed Shariff on my Joomla! website [systemtest.neudorf-mkk.de](url). Because I usually omit the starting www. in URLs, I also added the rewrite rule non-www to www. into .htaccess according to your documentation. After that installation, the front page loads okay, but in the backend the icons from the IcoMoon font are not shown:
![backend_without_icomoon_font](https://cloud.githubusercontent.com/assets/7933215/17248040/e68db72c-5597-11e6-9d96-ac71cdcb21d8.jpg)
The Firebug network protocol shows some 301 errors, including IcoMoon.woff and IcoMoon.ttf :
![backend_without_icomoon_font_firebug_network](https://cloud.githubusercontent.com/assets/7933215/17248041/e691f292-5597-11e6-8620-a56595f39a59.jpg)

Loading the backend with the www ([www.systemtest.neudorf-mkk.de](url)), IcoMoon icons are displayed. The behaviour is the same for Firefox and Edge (other browsers not tested).

Note:
The backend of systemtest.neudorf-mkk.de is secured by a .htaccess in the administrator directory with following content:
`AuthUserFile "/hp/au/ae/fl/www/neudorf2pre/administrator/.htpasswd"
AuthName "Restricted Area"
AuthType Basic
require valid-user

RewriteEngine On
RewriteRule \.htpasswd$ - [F,L]`

--------------------------------------------------------------------------------

To dig deeper into the issue, I installed a pure Joomla! 3.6.0 (no external extensions, no content but examples) in my webspace into a sub-subdirectory "Shariff" of www. I also added the rewrite rule non-www to www. into .htaccess according to your documentation. 
Here is what happens after entering these URLs:

_www.dautrich.eu/Shariff_ or _dautrich.eu/Shariff_
Page displays correctly, URL is shown as dautrich.eu/Shariff
![shariff_frontend_with_www](https://cloud.githubusercontent.com/assets/7933215/17248254/958def66-5599-11e6-9d9c-ccd5d284d903.jpg)

_www.dautrich.eu/Shariff/administrator_ or _dautrich.eu/Shariff/administrator_
Page displays correctly, URL is shown as dautrich.eu/Shariff/administrator
![shariff_backend_with_www](https://cloud.githubusercontent.com/assets/7933215/17248355/48d497e6-559a-11e6-9e8b-a157e5e124b2.jpg)

**Comment by ufuk-avcu** [comment]
Ich antworte mal auf deutsch. Das Problem scheint ja kein Problem der htaccess Umleitung aus meiner Anleitung sein. Sonst müsste das Problem ja auch auf der sauberen Installation auftreten. Ansonsten teste mal direkt die neueste Beta: https://github.com/joomla-agency/plg_jooag_shariff/releases/tag/3.3.0Beta2

**Comment by dautrich** [comment]
Trotzdem noch mal eine Nachfrage: Ist es korrekt, dass (mit der Umleitung non-www auf www) auch dann in der Adresszeile des Browser die URL ohne www. angezeigt wird, auch wenn ich sie mit www. eingebe (auf der sauberen Installation)?

Wegen der sonst fehlenden IcoMoon-Zeichen muss ich als Umgehungslösung die Administratorseite mit vorangestelltem www. aufrufen. Das ist im Prinzip nur eine Anpassung meiner Bookmarks.

Dass der Effekt bei meiner Seite auftritt, kann natürlich auch daran liegen, dass einige Erweiterungen installiert sind, z.B. JCHoptimize. Es ist mir aber momentan zu mühsam, alle Varianten auszuprobieren.

Die Beta-Version V3.3 werde ich mal ausprobieren.
