### ISSUE TITLE
3.3.0Beta1  -  Warning During Installation

### ISSUE THREAD

**Issue by dautrich** [joomla-agency/plg_jooag_shariff#32]
Installing the beta plugin, I get the error message:

> Warnung
JInstaller: :Install: Die Datei „/hp/au/ae/fl/www/neudorf2pre/tmp/install_579c7f6a3b009/plg_jooag_shariff-3.3.0Beta1/en-GB/en-GB.plg_system_jooag_shariff.ini“ existiert nicht.

**Comment by ufuk-avcu** [comment]
Please test the new Beta 2 Release: https://github.com/joomla-agency/plg_jooag_shariff/releases/tag/3.3.0Beta2
