### ISSUE TITLE
3.3.0Beta2  -  Shariff buttons not displayed in featured articles on homepage

### ISSUE THREAD

**Issue by dautrich** [joomla-agency/plg_jooag_shariff#35]
Shariff buttons were displayed in 3.3.0.Beta1, when the option "Show everywhere" was set, but in the new Beta, the option is no longer available.

**Comment by ufuk-avcu** [comment]
I try to show the Shariff Buttons in Categories Blog and Featured Article views. But there are some problems with multiple instances of the shariff Backend Counter. Because of that i deactivated this function.
