### ISSUE TITLE
3.3.0Beta2  -  Typo in German Introduction

### ISSUE THREAD

**Issue by dautrich** [joomla-agency/plg_jooag_shariff#36]
Correct spelling "dass" instead of "das" (s. attached)
![shariff_introduction_german](https://cloud.githubusercontent.com/assets/7933215/17286262/bd1d80a6-57c8-11e6-969f-df22c8bd723b.jpg)

**Comment by ufuk-avcu** [comment]
Fixed in the 3.3.0 Branch.
https://github.com/joomla-agency/plg_jooag_shariff/commit/b755a1896f6910b8f8593776b53176a9a129067e
