### ISSUE TITLE
Typo in Backend

### ISSUE THREAD

**Issue by flkoch** [joomla-agency/plg_jooag_shariff#38]
Explanation for shariff.min.css: Use if FontAwesome is already included! (reads FantAwesome, cf. attached image)
![image](https://cloud.githubusercontent.com/assets/18426845/22011057/3680f998-dc8d-11e6-9736-3d9355fe27be.png)

**Comment by ufuk-avcu** [comment]
Corrected in the newest 3.3.0 staging.
https://github.com/joomla-agency/plg_jooag_shariff/commit/6a5a2c23a22c5c73dbe3282f7822b8cac102d6d7
