### ISSUE TITLE
Datenschutzbeitrag lässt sich nicht wählen

### ISSUE THREAD

**Issue by sveneick** [joomla-agency/plg_jooag_shariff#4]
Wenn ich ein Beitrag für den Info-Button auswählen möchte, erhalte ich in der Konsole einen Javascript-Fehler und der beutrag lässt sich nicht auswählen.
![screen_u78vm](https://user-images.githubusercontent.com/4112464/39734886-66cdeb8e-5279-11e8-9617-b88f9eee7f5f.jpg)

**Comment by ufuk-avcu** [comment]
Ein kurzer Workaround für's erste: Wähle den Info-Button aus und speichere einmal das Plugin ab. Dann versuche den Beitrag aus dem PopUp auszuwählen und es sollte gehen.
