### ISSUE TITLE
Error at fresh install

### ISSUE THREAD

**Issue by StyrianOak** [joomla-agency/plg_jooag_shariff#44]
Hi!
I have Joomla 3.8.1, german + english, fresh install of plg_jooag_shariff shows error:

JInstaller: :Install: Die Datei „/tmp/install_59fb7b0284ad7/plg_jooag_shariff-master/css“ existiert nicht.
Plugin Installieren: Die Dateien konnte nicht kopiert werden.

Thx in advance for a hint - Klaus R.

**Comment by ufuk-avcu** [comment]
Corrected this in the 4.0.0 Branch. I release later today a new RC2.
