### ISSUE TITLE
Whatsapp only on mobile devices

### ISSUE THREAD

**Issue by janstieler** [joomla-agency/plg_jooag_shariff#48]
Hi,
is it possible to control the show of the socialnetwork buttons through the {shariff} shorttag?
My problem actually is that I want to show some buttons like Whatsapp only on mobile devices and with mediqueries it is not really proof because tabletsizes.
And there is a great libary [mobilededect](http://mobiledetect.net/) where is also served for joomla through [yagendoo](https://www.yagendoo.com/de/produkt/mobile-detection-joomla-plugin.html) and with the shorttag possibility I could publish multiple modules with different buttons.

or have you another idea how i can show whatsapp only on mobile devices?

Cheers

**Comment by AK-CCM** [comment]
Hi,

I think also this will be an important feature that the WhatsApp-Button is only shown on tablet devices and mobile phones.

If not it would be great that an useful hint message is shown for example:
"No WhatsApp is found on this device. Please install it or use [WhatsApp Web](https://web.whatsapp.com/)."

At the moment my browser (firefox dev) shows only an error message (sorry, only in German):
"Adresse nicht erkannt. Firefox weiß nicht, wie diese Adresse geöffnet werden soll, da eines der folgenden (whatsapp) kein registriertes Protokoll oder in diesem Kontext nicht erlaubt ist. Eventuell müssen Sie andere Software installieren, um diese Adresse aufrufen zu können."

Regards, Andreas

**Comment by ufuk-avcu** [comment]
Hey,

i told this some times before. We utilize the Shariff Library from https://github.com/heiseonline/shariff/ and they don't implement this feature, because of reasons i don't know. Some other people also ask for this here: https://github.com/heiseonline/shariff/issues/168 .

Best regards
