### ISSUE TITLE
Remove Bulletlist

### ISSUE THREAD

**Issue by thaliruth** [joomla-agency/plg_jooag_shariff#50]
Hello, Unfortunately, the whole thing is displayed as an enumeration for me. And the buttons are cut off. How can I remove this enumeration?
![bulletlist](https://user-images.githubusercontent.com/38152144/38452329-5bb3f260-3a42-11e8-8143-1d4969759712.PNG)

**Comment by thaliruth** [comment]
Yes it seems to conflict with my template. Do you have any idea how to fix this?

**Comment by ufuk-avcu** [comment]
Please ask your webdesigner for a solution. This this should be solved in a few easy steps.

**Comment by thaliruth** [comment]
Thank you very rude! The design I have created, I just need to know if I have to use the code in the expansion of the Myshariff or rather in my template, but there is something open source and is distributed with such an answer. Well, donations do not need money for the great project
