### ISSUE TITLE
Counter not showing

### ISSUE THREAD

**Issue by rweoli** [joomla-agency/plg_jooag_shariff#6]
I have done the steps (.htaccess & save the plugin) in the Documentation to activate the counter, but it doesnt show the Counter on the Website. Also the {shariff} shortcut doesnt work in the whole System. PHP ist 5.5.24 and Joomla ist 3.4.1. Can anyone help me?

**Comment by joomla-agency** [comment]
Counter:
On some Server Enviroments the counter don't works. Which host you use?
Shariff ShortCode:
This works only in the "Custom HTML" Module and with the activated "Prepare Content" option!

**Comment by rweoli** [comment]
Hi!

Counter: My Joomla is running on a Standard-Apache-Webserver. Should i post the Server-Info?
ShortCode: I have test it in the Custom HTML Module an the setting are correct.

For example: http://www.rot-weiss-erfurt.com/kalender.html

In the right Module, you see the Shortcut. On the bottom are the plugin.

Thank you for your effort!

**Comment by joomla-agency** [comment]
@rweoli can you give me SuperUser access to your site? info@joomla-agentur.de

**Comment by rweoli** [comment]
You should have an E-Mail.

**Comment by joomla-agency** [comment]
@rweoli the settings aren't correct: You have not set the Custom Module Setting Prepare Content(auf deutsch: Inhalte vorbereiten) to yes and in the plugin itself you should choose in the tab Design->Position->"Only in Module". Now you can see the working shariff Tag! The other Problem with the counter could depends on your server enviroment. You use PHP as in the apache2handler mode and most of your folder are not writable. You need to fix that first.

**Comment by rweoli** [comment]
Thank you for your effort!

If i use it only in modules, i can't use as plugin also? Actually it dont be displayed as plugin. Is this correct?

Which folders must be writeable? I can't find it in the documentation.
https://github.com/joomla-agency/plg_jooag_shariff/blob/master/README.md

**Comment by joomla-agency** [comment]
@rweoli yes, you can use the plugin only in a module or in content.
Folders:
It's not  a specific folder. You can see this in the Joomla Backend und System Informations. Most of the directory are not writable, because of the apache2handler Mode. Maybe this is the problem, because the Shariff Counter needs to write cache files to work!

**Comment by rweoli** [comment]
Sorry for annoying!

I have set all folders in the Joomla-Systeminfo to writeable. Joomla only accept 777 for status „writeable“. In my opinion its an security-risk but for this test i changed it. I want to use Shariff as plugin, so i changed the setting back to it. After the Change to writeable, the counter dont be displayed. Should i now reinstall the plugin?

**Comment by joomla-agency** [comment]
@rweoli the Folder & File Access rights have nothing to do with Joomla. It's the apache2handler Mode. 777 is off course not acceptable! You can google more about it under "wwwrun". I need some time to revisit the counter caching mechanism. But don't except to much in the next 3-6 Weeks. I have a ton of regular work and need at least some vacation!
