### ISSUE TITLE
How to retrieve the secret key of the API and the Facebook ID

### ISSUE THREAD

**Issue by sorgina** [joomla-agency/plg_jooag_shariff#6]
Hello

I just updated **JooAg Shariff to 4.0.1**, but I did not understand how to get the API secret key and ID. It is written that you have to go to **developers.facebook.com**, but after I did not understand where to go in this site. I went to **Start** but it asks to create an account. I really do not want to create another account on FB.

**Comment by ufuk-avcu** [comment]
Yes you need an another Facebook Login. Without thee Facebook API Login, you can't use the counter of this Plugin. https://goldplugins.com/documentation/wp-social-pro-documentation/how-to-get-an-app-id-and-secret-key-from-facebook/
