### ISSUE TITLE
Die buttons zeigen nur ein Ausrufe/Fragezeichen

### ISSUE THREAD

**Issue by Maqueez01** [joomla-agency/plg_jooag_shariff#7]
Hi, ich habe in joomla 3.8 das Plugin installiert und es über shortcode bei ausgewählten Artiken eingebunden. Es werden nur ausrufezeichen / Fragezeichen angezeigt statt der entsprechenden Logos FB, Twitter etc.
ich habe das shariff.complete.css aktiviert; allerdings ist es kein Unterschied wenn ich ens von den anderen CSS nehme. Hier der Link: 
https://legal-revolution.com/de/the-legal-revolutionary/jobs/legal-tech-jobangebot-001

Über einen Tip würde ich mich sehr freuen. 
Danke

**Comment by ufuk-avcu** [comment]
Besteht das Problem weiterhin? Ich sehe die Buttons bei auf deiner Seite.

**Comment by Maqueez01** [comment]
Hallo, nein ich habe den Grund inzwischen gefunden. auf der Seite war schon FontAwesome im Einsatz allerding Version5; das hat sich mit der im shariff verwendeten nicht vertragen. der Präfix musste von "fa" auf "fab" geändert werden, ich habe die shariff.min.css herangezogen, so geht es jetzt. 
Vielen dank für die Reaktion und Nachfrage.
