### ISSUE TITLE
Path not in open_basedir paths

### ISSUE THREAD

**Issue by brunosaetta** [joomla-agency/plg_jooag_shariff#7]
Hi, great plugin, I love it :-) 
Unfortunately I have a problem. 
On web site it displays this warning: "JFolder::create: Path not in open_basedir paths"
I checked the openbase parameter, it's ok. And all directory are writable. How I fix it? :-(

**Comment by joomla-agency** [comment]
Can you test the newest release again please?

**Comment by brunosaetta** [comment]
Upload new realese, but always the same warning. :-(

**Comment by joomla-agency** [comment]
Can you provide more information: Login and http://yourdomain.de/administrator/index.php?option=com_admin&view=sysinfo and your hosting company?

**Comment by brunosaetta** [comment]
Hi, here is the info: 

PHP attivo su 	Linux halley.myprivatehosting.biz 2.6.32-531.29.2.lve1.3.11.1.el6.x86_64 #1 SMP Thu Dec 18 06:49:17 EST 2014 x86_64
Versione database 	5.1.73-cll-lve
Collation database 	utf8_general_ci
Versione PHP 	5.4.40
Web Server 	Apache
WebServer interfaccia PHP 	cgi-fcgi
Versione di Joomla! 	Joomla! 3.4.3 Stable [ Ember ] 2-July-2015 16:00 GMT
Versione piattaforma Joomla! 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0 

Provider 	Keyweb AG (AS31103)

**Comment by joomla-agency** [comment]
Hi Thank you. Can you provide the Informations from the second Tab called "PHP Settings", too?

**Comment by brunosaetta** [comment]
Impostazione 	Valore
 
Safe Mode 	No
Open basedir 	/data/vhosts/jomguide.it:/tmp
Display Errors 	No
Short Open Tags 	Sì
Caricamento file 	Sì
Magic Quotes 	No
Register Globals 	No
Output Buffering 	No
Percorso salvataggio sessione 	Nessuno
Auto start sessione 	0
XML abilitato 	Sì
Zlib abilitato 	Sì
ZIP nativo abilitato 	Sì
Funzioni disabilitate 	Nessuno
Mbstring abilitato 	Sì
Iconv disponibile 	Sì

**Comment by joomla-agency** [comment]
I think the problem is this setting: Open basedir /data/vhosts/jomguide.it:/tmp . Can you set this to none?

**Comment by brunosaetta** [comment]
In the configuration.php is set to: 
tmp_path 	/data/vhosts/jomguide.it/httpdocs/tmp

**Comment by brunosaetta** [comment]
The provider says that isn't possible to set to none for security concerns :-(

**Comment by joomla-agency** [comment]
Maybe this is a workaround for your problem: Create this folder manually in your cache folder:
joomla_root/cache/plg_jooag_shariff . An another way (not recommended) is to activate the Joomla FTP Layer in the Global Configuration.

**Comment by joomla-agency** [comment]
Can you test the newest Version please? https://github.com/joomla-agency/plg_jooag_shariff/releases/tag/3.0.6RC4

**Comment by brunosaetta** [comment]
Yeah, looks like it works fine now. Thank you :-)

**Comment by joomla-agency** [comment]
No Problem! Solved with https://github.com/joomla-agency/plg_jooag_shariff/commit/061e1b0fc5fdbea5e7d5c0d8cb4b8340f9dcba25
