### ISSUE TITLE
Enter Facebook app_id and secret via plugin settings

### ISSUE THREAD

**Issue by CommanderBond** [joomla-agency/plg_jooag_shariff#9]
According to https://github.com/heiseonline/shariff-backend-php, Facebook service has two options in shariff.json for app_id and secret that allows to use Graph API 2.2 calls to query Facebook counters (should be more reliable and more exact).

Could you please provide those two input fields in plugin settings (settings tab). They may be visible/activated, if Counter/Zähler setting is set to "activated".

Thanks

**Comment by CommanderBond** [comment]
Syntax for those options is described here (should be integrated in Shariff Readme):
https://github.com/heiseonline/shariff-backend-php/issues/36

**Comment by joomla-agency** [comment]
Solved here: https://github.com/joomla-agency/plg_jooag_shariff/commit/9e8687b3baba11d2616fd24da85a689f5229f3e6
